# Generated by Django 2.0 on 2018-08-23 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dosu', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
