# Generated by Django 2.0 on 2018-08-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='dosu',
            field=models.FloatField(),
        ),
    ]
